use the embedded ruby template to generate caasp-kvm/cluster.tf

diff --git a/caasp-kvm/caasp-kvm b/caasp-kvm/caasp-kvm
--- a/caasp-kvm/caasp-kvm
+++ b/caasp-kvm/caasp-kvm
@@ -8,6 +8,7 @@ DIR="$( cd "$( dirname "$0" )" && pwd )"
 ACTION=
 RUN_BUILD=
 RUN_DESTROY=
+QA=${QA:-}
 
 MASTERS=${CAASP_NUM_MASTERS:-1}
 WORKERS=${CAASP_NUM_WORKERS:-2}
@@ -62,6 +63,9 @@ Usage:
     --worker-ram <INT>     CPUs to allocate to master node(s) (Default: CAASP_MASTER_CPU=$MASTER_CPU)
     --master-cpu <INT>     RAM to allocate to worker node(s) (Default: CAASP_WORKER_RAM=$WORKER_RAM)
     --worker-cpu <INT>     CPUs to allocate to worker node(s) (Default: CAASP_WORKER_CPU=$WORKER_CPU)
+
+  * Even more advanced options
+    --qa                   ignore local git checkouts and use the image as it is for QA
 
   * Examples:
 
@@ -154,6 +158,9 @@ while [[ $# > 0 ]] ; do
       WORKER_CPU="$2"
       shift
       ;;
+    --qa)
+      QA="true"
+      ;;
     -h|--help)
       usage
       ;;
@@ -198,7 +205,7 @@ build() {
   log "Downloading CaaSP KVM Image"
   $DIR/../misc-tools/download-image --proxy "${PROXY}" --type kvm $IMAGE
 
-  if [ -n "$CAASP_VELUM_DIR" ] ; then
+  if [ -n "$CAASP_VELUM_DIR" -a "$QA" != "true" ] ; then
     log "Building Velum Development Image"
     $DIR/tools/build-velum-image "$CAASP_VELUM_DIR" "${PROXY}"
 
@@ -215,6 +222,9 @@ build() {
   else
     log "Skipping Velum environment"
   fi
+
+  log "Generating terraform manifest from erb template"
+  erb -T - cluster.tf.erb > cluster.tf || error "Failed to generate cluster.tf, check that erb is installed correctly"
 
   log "Applying terraform configuration"
   terraform init && terraform apply $TF_ARGS
