DevEnv: Install lsb-release before we try and use it

diff --git a/caasp-devenv b/caasp-devenv
--- a/caasp-devenv
+++ b/caasp-devenv
@@ -40,6 +40,7 @@ EXTRA_REPO=${CAASP_EXTRA_REPO:-}
 
 # base distribution used for setting up dependencies, and the packages to install
 DIST_BASE="opensuse.org/repositories/Virtualization:/containers"
+EARLY_DIST_PACKAGES="lsb-release"
 DIST_PACKAGES="jq \
                python-tox \
                python-devel \
@@ -51,7 +52,6 @@ DIST_PACKAGES="jq \
                terraform \
                ruby-devel \
                gcc \
-               lsb-release \
                make \
                terraform-provider-libvirt \
                guestfs-tools \
@@ -241,6 +241,9 @@ export ENVIRONMENT="$DIR/caasp-kvm/environment.json"
 # Core methods
 setup() {
   log "Installing CaaSP Development Environment Requiemnts"
+  # || : is necessary, as Zypper exits non-zero for "no changes".
+  sudo zypper in --no-confirm $EARLY_DIST_PACKAGES || :
+
   local dist=$(lsb-release -sd | tr -d '"' | tr " " "_")
 
   if ! zypper lr -dU | grep --quiet "suse.de/ibs/SUSE:/CA" ; then
